### ISSUE TITLE
Find recipes that conform to specific diet/dietary restrictions

### ISSUE THREAD

**Issue by icn2you** [icn2you/fsf-p01#2]
## Specific Diet/Dietary Restrictions
As a user, I want to find recipes that conform to my specific diet/dietary restrictions.

### Frontend
- [x] index.html has a list of checkboxes showing the most popular diet types/dietary restrictions (*e.g.*, vegan, gluten-free, etc.). - Chris
- [x] index.html has a form field that takes text input in which user can list a specific ingredient to include in search. - Chris
- [x] index.html has an Add Ingredient button after user inputs each ingredient. - Chris
- [ ] index.html has a search button. - Chris

### Backend
- [ ] ...
- [ ] ...
- [ ] ...

**Comment by yuda0110** [comment]
Created a wire frame for index.html.

`https://wireframe.cc/6HJ6Ax` 


![index](https://user-images.githubusercontent.com/34582558/77816240-7e936300-707e-11ea-9753-9d737d840ea7.png)
