### ISSUE TITLE
Modify recipe portions to feed specified number of people

### ISSUE THREAD

**Issue by icn2you** [icn2you/fsf-p01#4]
## Modify Portions
As a user, I want to be able to modify recipe portions to feed my specific number of people.

### Frontend
- [ ] recipe.html displays a recipe that the user selected. - Chris
- [ ] recipe.html displays a title of the dish/meal. - Chris
- [ ] recipe.html displays directions for preparing the meal. - Chris
- [ ] recipe.html displays a photo of the finished product. - Chris
- [ ] recipe.html displays a dropdown form field that the user can use to select the number of people s/he is trying to feed. - Chris
- [ ] recipe.html changes ingredient portions in realtime based on the user's input. - Chris

### Backend
- [ ] ...
- [ ] ...
- [ ] ...

**Comment by yuda0110** [comment]
Created a wire frame for recipe-[recipeID].html.

[https://wireframe.cc/zUlS2y](url)


![recip-id](https://user-images.githubusercontent.com/34582558/77816866-afc26200-7083-11ea-9c33-e6e46207738c.png)
