### ISSUE TITLE
Find recipes that are simple, delicious, and quick to make.

### ISSUE THREAD

**Issue by icn2you** [icn2you/fsf-p01#5]
## Simple and Delicious Recipes
As a user, I want to find recipes that are simple (i.e., six ingredients or less), delicious, and 30 minutes to cook or less.

### Frontend
- [ ] recipes.html displays results of search query as a list of cards. - Chris
- [ ] Each card on recipes.html displays a thumbnail of the dish/meal. - Chris
- [ ] Each card on recipes.html displays the title of the meal. - Chris
- [ ] Each card lists the diet type/dietary restrictions the dish/meal meets. - Chris
- [ ] Each card lists the cooking time. - Chris
- [ ] Each card on recipes.html displays a brief description of the dish/meal. - Chris

### Backend
- [ ] ...
- [ ] ...
- [ ] ...

**Comment by yuda0110** [comment]
Created a wire frame for index.html.

[https://wireframe.cc/C8Vwof](url)


![recipes](https://user-images.githubusercontent.com/34582558/77816547-b4d1e200-7080-11ea-8f64-465eff468b27.png)
